# Inserts a blank line between shell prompts
add_newline = true

format='''
[╭─](bold purple)[ ](bold purple)$directory
[╰──](bold purple)$character
'''

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[battery]
disabled = true

[character]
success_symbol = "💙[❯](bold green)"
error_symbol = "💔[❯](bold red)"
